### ISSUE TITLE
AttributeError: 'FetchFromCacheMiddleware' object has no attribute 'cache_anonymous_only'

### ISSUE THREAD

**Issue by nethernuit** [peterbe/django-fancy-cache#26]
Hi Peter, 
first of all, I wanted to thank you for the nice piece of software you wrote. 
Django 1.9 and Python 3.5:

I added your code to my project by doing a drop in replacement of the UpdateCacheMiddleware and FetchFromCacheMiddleware classes:
e.g. in my settings:

```
MIDDLEWARE_CLASSES = (
'fancy_cache.middleware.UpdateCacheMiddleware',
...,
'fancy_cache.middleware.FetchFromCacheMiddleware',
)
```

I then added this annotation into my 'url.py':
`cache_page(cache_timeout= 600, forget_get_keys=['draw'],post_process_response_always=replace_draw_id)(MyClassView.as_view())`

This created the following error:

```
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 123, in get_response
response = middleware_method(request)
File "/basic/fancy_cache/middleware.py", line 167, in process_request
response = self._process_request(request)
File "/basic/fancy_cache/middleware.py", line 182, in _process_request
if self.cache_anonymous_only:
AttributeError: 'FetchFromCacheMiddleware' object has no attribute 'cache_anonymous_only'
```

Looking at the code, there is no __init__ function for both classes. Just copying __init__ from 
**CacheMiddleware** fixes the problem.

**Comment by peterbe** [comment]
Sorry for late reply. Would you be interesting in writing a PR to fix this?

When I built this project I just copied the default middlewares from django and updated them to be more "fancy". Things have changed in recent django releases and I think it's clear that this project is missing some of those changes. 

The best thing would be to use object orientation to call out to a super class.

**Comment by nethernuit** [comment]
yes I can do that. Likely within the next two weeks.

**Comment by YPCrumble** [comment]
@peterbe this was resolved by #64
